database:
  file: "database.db"
  table-prefix: "sincegps_"

settings:
  # Khoảng cách tìm điểm bắt đầu (blocks)
  nearest-node-search-range: 100.0
  # Khoảng cách tính là "đến nơi"
  reach-distance: 3.0
  # Độ mượt đường cong (8-12)
  curve-resolution: 8
  # Tốc độ cập nhật (1 = mượt nhất)
  update-rate: 1

  # Cấu hình Ghi hình (Admin)
  recorder:
    min-distance: 8.0       # Đi xa X block mới tạo node
    angle-threshold: 15.0   # Góc cua > X độ tạo node ngay
    snap-distance: 3.0      # Khoảng cách tự bắt dính đường cũ

  # Cấu hình Dẫn đường (Player)
  navigation:
    reroute-distance: 12.0  # Lệch X mét -> Tính lại đường
    check-interval: 20      # Check mỗi 1 giây

# Hiệu ứng hình ảnh
visuals:
  view-distance: 60.0

  # Hiệu ứng cho người chơi (Khi đi theo GPS)
  navigation:
    path-type: REDSTONE
    path-color: "0, 255, 255"  # Cyan
    pulse-type: REDSTONE
    pulse-color: "255, 165, 0" # Orange
    pulse-speed: 1.5
    arrow-enabled: true

  # Hiệu ứng cho Admin (Khi đang Record)
  recorder:
    node-normal: FLAME           # Các node cũ
    node-new: HAPPY_VILLAGER     # Node vừa tạo
    node-snap: SOUL_FIRE_FLAME   # Node bắt dính
    edge-line: CRIT              # Dây nối

action-bar:
  enabled: true
  arrows:
    forward: "⬆"
    left: "⬅"
    right: "➡"
    backward: "⬇"
  format: "<yellow><bold><arrow> <white>Đi về phía trước <gold><dist>m"

groups:
  default:
    permission: ""
    navigable: true
  admin:
    permission: "gps.group.admin"
    navigable: true

sounds:
  start:
    enabled: true
    type: BLOCK_BEACON_ACTIVATE
    volume: 1.0
    pitch: 2.0
  stop:
    enabled: true
    type: BLOCK_NOTE_BLOCK_BASS
    volume: 1.0
    pitch: 0.5
  arrive:
    enabled: true
    type: UI_TOAST_CHALLENGE_COMPLETE
    volume: 1.0
    pitch: 1.0
  popup:
    enabled: true
    type: ENTITY_VILLAGER_NO
    volume: 1.0
    pitch: 1.0
  snap:
    enabled: true
    type: BLOCK_NOTE_BLOCK_PLING
    volume: 1.0
    pitch: 2.0